site_name: MkLorum
site_url: https://example.com/

nav:
    - Home: index.md
    - About: about.md
    - Models: models.md

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_submodules: true

# Render LaTeX with MathJax
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      # Enables $ for inline math.
      enable_dollar_delimiter: true
